#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates fast C lookup code for known string sets

puts "/* This file is auto-generated by #{__FILE__} */"
puts

class StringLookup
  def initialize
    @string_table = Hash.new do |h, k|
      h[k] = name_for_string(k)
    end
    @functions = []
  end

  def generate
    @string_table.each do |v, name|
      puts "static VALUE #{name}; /* #{v.inspect} */"
    end
    puts

    @functions.each do |code|
      puts code
      puts
    end

    puts "static void init_string_lookup(void) {"
    @string_table.each do |v, name|
      puts "  rb_gc_register_address(&#{name});"
      puts "  #{name} = rb_interned_str_cstr(#{v.dump});"
    end
    puts "}"
    puts
  end

  def name_for_string(string)
    "rb_s_#{string.gsub(/[^a-z0-9]/i, "_")}"
  end

  def generate_comparison(var, string, ignore_case: false)
    0.upto(string.length - 1).map do |i|
      if ignore_case
        "(#{var}[#{i}] | 32) == '#{string[i].downcase}'"
      else
        "#{var}[#{i}] == '#{string[i]}'"
      end
    end.join(" && ")
  end

  def add_function(function, mapping, ignore_case: false)
    if mapping.is_a?(Array)
      mapping = mapping.map do |str|
        [str, str]
      end.to_h
    end
    by_length = mapping.group_by do |(k,v)|
      k.length
    end

    code = []
    code << "static VALUE lookup_#{function}(const char *s, size_t len) {"
    code << "  switch (len) {"

    by_length.sort.each do |len, strs|
      code << "  case #{len}:"
      strs.each do |match, target|
        name = @string_table[target]
        code << "    if (#{generate_comparison("s", match, ignore_case:)}) return #{name};"
      end
      code << "    break;"
    end

    code << "  }"
    code << "  return Qnil;"
    code << "}"

    @functions << code.join("\n")
  end
end

HEADERS = %w[Content-Type Content-Length Host User-Agent Accept Accept-Encoding
             Accept-Language Connection Cache-Control Cookie Authorization Referer]

METHODS = %w[GET POST PUT DELETE HEAD OPTIONS PATCH]

lookup = StringLookup.new
header_mapping = HEADERS.map do |header|
  header = header.downcase
  rack_key = header.upcase.gsub("-", "_")
  unless header == "content-type" || header == "content-length"
    rack_key = "HTTP_#{rack_key}"
  end
  [header, rack_key]
end.to_h
lookup.add_function("header", header_mapping, ignore_case: true)
lookup.add_function("method", METHODS)
lookup.generate
