#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates fast C lookup code for known string sets

puts "/* This file is auto-generated by #{__FILE__} */"
puts

class StringLookup
  def initialize
    @string_table = Hash.new do |h, k|
      h[k] = name_for_string(k)
    end
    @functions = []
  end

  def generate
    # Generate the struct to hold all strings
    puts "static struct string_lookup_t {"
    @string_table.each do |v, name|
      puts "  VALUE #{name}; /* #{v.inspect} */"
    end
    puts "} string_lookup;"
    puts

    @functions.each do |code|
      puts code
      puts
    end

    # Generate mark function
    puts "static void string_lookup_mark(void *ptr) {"
    puts "  struct string_lookup_t *s = ptr;"
    @string_table.each do |v, name|
      puts "  rb_gc_mark_movable(s->#{name});"
    end
    puts "}"
    puts

    # Generate compact function
    puts "static void string_lookup_compact(void *ptr) {"
    puts "  struct string_lookup_t *s = ptr;"
    @string_table.each do |v, name|
      puts "  s->#{name} = rb_gc_location(s->#{name});"
    end
    puts "}"
    puts

    # Generate TypedData type
    puts "static const rb_data_type_t string_lookup_type = {"
    puts "  .wrap_struct_name = \"picohttp_string_lookup\","
    puts "  .function = {"
    puts "    .dmark = string_lookup_mark,"
    puts "    .dfree = NULL,"
    puts "    .dsize = NULL,"
    puts "    .dcompact = string_lookup_compact,"
    puts "  },"
    puts "  .flags = RUBY_TYPED_FREE_IMMEDIATELY | RUBY_TYPED_WB_PROTECTED,"
    puts "};"
    puts

    puts "static void intern_str(VALUE wrapper, VALUE *field, const char *str) {"
    puts "  RB_OBJ_WRITE(wrapper, field, rb_interned_str_cstr(str));"
    puts "}"
    puts

    puts "static void init_string_lookup(void) {"
    puts "  VALUE wrapper = TypedData_Wrap_Struct(0, &string_lookup_type, &string_lookup);"
    puts "  rb_gc_register_mark_object(wrapper);"
    @string_table.each do |v, name|
      puts "  intern_str(wrapper, &string_lookup.#{name}, #{v.dump});"
    end
    puts "}"
    puts
  end

  def name_for_string(string)
    string.gsub(/[^a-z0-9]/i, "_").downcase
  end

  def generate_comparison(var, string, ignore_case: false)
    0.upto(string.length - 1).map do |i|
      if ignore_case
        "(#{var}[#{i}] | 32) == '#{string[i].downcase}'"
      else
        "#{var}[#{i}] == '#{string[i]}'"
      end
    end.join(" && ")
  end

  def add_function(function, mapping, ignore_case: false)
    if mapping.is_a?(Array)
      mapping = mapping.map do |str|
        [str, str]
      end.to_h
    end
    by_length = mapping.group_by do |(k,v)|
      k.length
    end

    code = []
    code << "static VALUE lookup_#{function}(const char *s, size_t len) {"
    code << "  switch (len) {"

    by_length.sort.each do |len, strs|
      code << "  case #{len}:"
      strs.each do |match, target|
        name = @string_table[target]
        code << "    if (#{generate_comparison("s", match, ignore_case:)}) return string_lookup.#{name};"
      end
      code << "    break;"
    end

    code << "  }"
    code << "  return Qnil;"
    code << "}"

    @functions << code.join("\n")
  end
end

HEADERS = %w[Content-Type Content-Length Host User-Agent Accept Accept-Encoding
             Accept-Language Connection Cache-Control Cookie Authorization Referer]

METHODS = %w[GET POST PUT DELETE HEAD OPTIONS PATCH]

lookup = StringLookup.new
header_mapping = HEADERS.map do |header|
  header = header.downcase
  rack_key = header.upcase.gsub("-", "_")
  unless header == "content-type" || header == "content-length"
    rack_key = "HTTP_#{rack_key}"
  end
  [header, rack_key]
end.to_h
lookup.add_function("header", header_mapping, ignore_case: true)
lookup.add_function("method", METHODS)
lookup.generate
